markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: jing1718.github.io
title: 张晶晶
description: Java, Linux, Hadoop, Spark
author: 张晶晶
email: jing1718#163.com
github: jing1718

encoding: UTF-8

config:
  js_dir:
  img_dir:
  css_dir:
